### <span style="font-family: 'Segoe Print';">**NUMPY PACKGE** IN PYTHON:
***

<span style="font-family: 'Segoe UI';">

* NumPy package is an acronynm for **'Numeric Python'**. 

* It was created by Travis Oliphant in 2005.

**Fundamental objective:**

> It is majorly used to create Homogeneous Multi-dimensional array.

> It has an associated fast math functions that operate on it.

> It also provides simple routines for linear algebra and FFT (Fast Fourier Transform) and sophisticated random-number generation. 

#### **<span style="font-family: 'Segoe Print';">I. Creating an Array:**

#### <span style="font-family: 'Segoe Print';">Arrays:

* An array is a collection of items stored at contiguous memory locations. 
* Arrays store homogeneous elements, i.e, elements belonging to same data type. 
* Elements can be randomly accessed using indices of an array.

In [6]:
#importing numpy package
import numpy as np

a=np.array([1,2,3]) #forming an array with 3 elements using array function in numpy
print("a = ",a)
np.array

#Accessing elements using indices
print("a[0] = ",a[0],"\na[2] = ",a[2])

a =  [1 2 3]
a[0] =  1 
a[2] =  3


### **<span style="font-family: 'Segoe Print';">II. Creating 2D arrays:**

* Two dimensional array are arrays within array.
* It is an array of arrays.
* It can be visualised as a grid (or table) with rows and columns.

Considering an array, 

    x = [[1 2 3]
         [4 5 6]]

* One can easily observe that x contains two sub-arrays, '[1 2 3]' & '[4 5 6]'. Hence, array of arrays makes sense. 
* 'x' contains two rows and 3 columns. 
* In the Numpy package, 'np.array()' takes few arguements,some of them are:

    *object* = Array like object

    *dtype* = Data type of the desired array. 

    *ndmin* = Minimum dimensions. 

In [7]:
x=np.array([[1,2,3],[4,5,6]])
print("x =\n",x)

x1=np.array([1,2,3,4,5],ndmin=2) 
print("Array x1 =",x1)

x =
 [[1 2 3]
 [4 5 6]]
Array x1 = [[1 2 3 4 5]]


### <span style="font-family: 'Segoe Print';">III. By observing these two arrays, a question comes to mind: 
**<span style="font-family: 'Segoe Print';">Are the arrays 'x' and 'x1' both 2 dimensional?**

* Yes, both 'x' and 'x1' is 2 dimensional. Here's why,

    > 'x' as declared is two dimensional, containing two sub-arrays.
    
    > While declaring x1, we passed an arguement, *ndmin=2* which specifies minimum dimension of the array as 2.

* In order to check the dimensionality of the array, we will use 'shape' or 'ndim' property. 

* **Shape Property:** Gives the dimension in the form of tuple (n,m) where 
                    n= number of rows and m=number of columns
                    
* **ndim property:** Gives the dimension of the array in the form of integer.

Let's do it! 

In [8]:
print("Dimension of x = ",x.shape)
print("Dimension of x1 = ",x1.shape) 
x.ndim #ndim gives the dimension of the array in the form of integer.

Dimension of x =  (2, 3)
Dimension of x1 =  (1, 5)


2

### <span style="font-family: 'Segoe Print';">IV. Using **'reshape(n,m)'** function:

* It is used to reshape/reverse the dimension of the array. 
* It takes the elements of the array serially converting it to the reverse array.
For the (2,3) dimsional array,
        
        x = [[1 2 3] 
            [4 5 6]]
         
Using ```x.reshape(3,2)``` would change the dimension the dimension of the array to (3,2). 

Storing the reshaped array in the varibale x2, it would look like,
 
    x2 = [[1 2]
          [3 4]
          [5 6]]

Here's how we use it.

In [9]:
# using reshape function on 'x' and storing it in variable 'x2'.
x2=x.reshape(3,2)
print("Dimesnion of the array 'x' after reshaping = ",x2.shape)
print("Reshaped array = \n",x2)

Dimesnion of the array 'x' after reshaping =  (3, 2)
Reshaped array = 
 [[1 2]
 [3 4]
 [5 6]]


### <span style="font-family: 'Segoe Print';">V. **'transpose()'** function:

* 'transpose()' is used to transpose the dimension of the array.

For e.g, if we have an array 'y' with dimension (2,3), then using transpose function we can reverse the dimension to (3,2).

Here's how we do it.

In [10]:
y=np.array([[1,2,3],[2,2,3]]) #creating an array 'y'.
print("Dimension of 'y'= ",y.shape) #checking the dimension of the array 'y'.

y1=y.transpose() #using transpose function to reverse the dimension and storing it in the variable y1.
print("Dimension of y after transposing =",y1.shape) #printing the dimension of 'y1'.

Dimension of 'y'=  (2, 3)
Dimension of y after transposing = (3, 2)


### <span style="font-family: 'Segoe Print';">VI. **Mathematical Operations** on arrays/matrices:

* All the mathematical operations (addition, subtraction, mulitplication and division) have been performed in two ways, shown below in the code cell.
* For sqaure root, in-built sqrt function in numpy has been used.

In [11]:
add=x + y #adding x and y
print("x + y = \n",add)
print("Using Function:\nx + y = \n",np.add(x,y)) #an alternative way to add x and y would be to use 'Add function'.

sub=x - y #subtracting x and y
print("x - y = \n",sub)
print("Using Function:\nx - y = \n",np.subtract(x,y)) #Subtracting using function

mult=x*y #multiplying x and y
print("x * y = \n",mult)
print("using Function:\nx * y = \n",np.multiply(x,y)) #multiplying using function

div=x / y #dividing x and y
print("x/y = \n",div)
print("Using Function:\nx / y = \n",np.divide(x,y)) #division using function

sqrt=np.sqrt(x) 
print("square root of 'x' = \n",sqrt) #calculating square root using sqrt() function in numpy. 

x + y = 
 [[2 4 6]
 [6 7 9]]
Using Function:
x + y = 
 [[2 4 6]
 [6 7 9]]
x - y = 
 [[0 0 0]
 [2 3 3]]
Using Function:
x - y = 
 [[0 0 0]
 [2 3 3]]
x * y = 
 [[ 1  4  9]
 [ 8 10 18]]
using Function:
x * y = 
 [[ 1  4  9]
 [ 8 10 18]]
x/y = 
 [[1.  1.  1. ]
 [2.  2.5 2. ]]
Using Function:
x / y = 
 [[1.  1.  1. ]
 [2.  2.5 2. ]]
square root of 'x' = 
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [133]:
#For dot multiplication, the number of columns of first array = number of rows of the second array. 
# So, we will use 'y1' (the transposed array of 'y') as the second array.
product = x.dot(y1)
print("Multiplication of 'x' and 'y1' = \n",product)

Multiplication of 'x' and 'y1' = 
 [[14 15]
 [32 36]]


### <span style="font-family: 'Segoe Print';">VII. **Trigonometrical functions** on above defined arrays/matrices:

In [134]:
sin=np.sin(mult)
cos=np.cos(mult)
print("sin of (x.y) = \n",sin,"\ncos of (x.y) = \n",cos)

sin of (x.y) = 
 [[ 0.84147098 -0.7568025   0.41211849]
 [ 0.98935825 -0.54402111 -0.75098725]] 
cos of (x.y) = 
 [[ 0.54030231 -0.65364362 -0.91113026]
 [-0.14550003 -0.83907153  0.66031671]]


<span style="font-family: 'Segoe Print';">We know,

$$ \sin^2{\theta} + cos^2{\theta} = 1 $$

<span style="font-family: 'Segoe Print';">This is exactly whats been done below by taking, 
$$ \theta = x.y 
$$


In [135]:
res=sin**2 + cos**2
print("sin^2(x.y) + cos^2(x.y) = \n",res)

sin^2(x.y) + cos^2(x.y) = 
 [[1. 1. 1.]
 [1. 1. 1.]]


* Now, what if we dont want the dot(.) at the end of every element in the above matrix. 
* The simplest solution will be to convert the data type of the array to integer which can be done using 'astype' function. 

    Here's how its done.

In [136]:
res=res.astype(int)
print(res)

[[1 1 0]
 [1 1 1]]


#### <span style="font-family: 'Segoe Print';">**Greattttt!!!!!!! So far, so good.**

### <span style="font-family: 'Segoe Print';">VIII. Slicing in **Arrays**:

        p = [1 2 3 4 5 6]
        x = [[1 2 3]
             [4 5 6]]

In [137]:
p=np.array((1,2,3,4,5,6))

s1=p[1:5] #slicing to pull out a sub-array that contains elements from index 1 to 4th.
print("Slicing in 'p'[1:5] = ",s1) #printing the array s1

s2=p[:2:3] #slicing the element 
print("Slicing in 'p'[:2:3] =",s2)


#Considering the 2D array x (declared above)
print("x=",x)
print(x[0,1])

s3=x[:2,1:3] #slicing to pull out a sub-array consisting of first 2 rows and columns 1 and 2
print("Slicing of 'x'[:2,1:3] = ",s3)

Slicing in 'p'[1:5] =  [2 3 4 5]
Slicing in 'p'[:2:3] = [1]
x= [[1 2 3]
 [4 5 6]]
2
Slicing of 'x'[:2,1:3] =  [[2 3]
 [5 6]]


In [138]:
row_0=x[0,:]
print(row_0,row_0.shape) #prints first row of 'x' along with the dimension (3,)

row_1=x[1,:]
print(row_1,row_1.shape) #prints second row of 'x' along with dimension (3,)

row_2=x[1:2,:]
print(row_2,row_2.shape) #prints second row with dimension (1,3)


[1 2 3] (3,)
[4 5 6] (3,)
[[4 5 6]] (1, 3)


In [139]:
#Accessing columns through slicing
col_0=x[:,0]
print(col_0,col_0.shape) #prints column 1 with dimension (2,)

col_1=x[:,1]
print(col_1,col_1.shape) #prints column 2 with dimension (2,)

col_2=x[:,1:2]
print(col_2,col_2.shape) #prints the second column with dimension (2,1)

[1 4] (2,)
[2 5] (2,)
[[2]
 [5]] (2, 1)


##### <span style="font-family: 'Segoe Print';">VIII. I was having some random questions related to arrays, in general.

> ##### *Lets look at the questions and answers one by one. Shall we?*

#### **Q.1] What if we want to find the sum of the elements of the array?**

Considering the matrix x,

    x =  [1   2   3]  
         [4   5   6]

sum = 21

We will be using 'sum()' to find the sum of the elements in the 2D array 'x'.

In [140]:
sum=np.sum(x)
print(sum)

21


#### **Q.2] What if we want to find the minimum value among the elements in the array 'x'?**

In [141]:
min=np.min(x)
print(min)

1


#### **Q.3] What if we want to create zero matrix of order 2*2?**

In [142]:
zero_matrix=np.zeros((2,2),dtype=int)
print(zero_matrix)

[[0 0]
 [0 0]]


#### **Q.4] What if we want to create a square matrix with just ones(1)?**

In [143]:
one_matrix=np.ones((2,2),dtype=int)
print(one_matrix)

[[1 1]
 [1 1]]


#### **Q.5] What if we want to create a unit matrix of order 2*2?**

In [144]:
unit_matrix=np.eye(2,dtype=int)
print(unit_matrix)

[[1 0]
 [0 1]]


#### **Q.6] What if we want to create a matrix with any constant number? other than one(1)?**

In [145]:
const=np.full((2,2),7.64)
print(const)

[[7.64 7.64]
 [7.64 7.64]]


#### **Q.7] What if we want to create a matrix with random numbers?**

- We use 'random' function from Random module to generate random numbers in an array 
- In case we want random array of integers, we would use 'randint (low, high, size)' function which takes 3 arguements:

    *low*=Lowest value

    *high*=highest value
    
    *size*=size of the array

In [146]:
random=np.random.random((2,2))
print("Random 2D array of numbers = \n",random)

random1=np.random.randint(100,500,50)
print("Random array of integers = \n",random1)

Random 2D array of numbers = 
 [[0.16110683 0.24764877]
 [0.86656536 0.22148099]]
Random array of integers = 
 [339 426 110 365 271 189 250 245 322 380 226 448 100 154 269 117 400 297
 366 379 115 288 390 473 340 310 324 240 154 310 188 263 118 284 353 433
 123 441 368 150 193 248 197 476 341 139 230 201 277 135]


##### <span style="font-family: 'Segoe Print';">IX. Creating a random array 'b' with 30 numbers, serially from 1 to 30, taking dimension (3,10) which suggests 3 rows having 10 columns.

- We are creating the array using 'np.arange()' function which takes 4 argurments, namely: 

    - start = The starting point/number of the array.
    - stop = the end point/number of the array.
    - dtype = Desired data type of the array.
    - like = object like array. By default ```like=None```

- Using 'reshape()' to shape rthe structure of the array. 

In this case, we have given, ```b=np.arange(30).reshape(3,10)``` , that means, the values 1 to 30 will be stored in an array 'b' having 3 rows and 10 columns.

In [147]:
b=np.arange(30).reshape(3,10) #np.arange( )
print(b)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
