## Lets discuss **NumPy Package** in Python:

* NumPy package is an acronynm for **'Numeric Python'**. 

* It was created by Travis Oliphant in 2005.

Fundamental objective:

    It is majorly used to create Homogeneous Multi-dimensional array.

    It has an associated fast math functions that operate on it.
    
    It also provides simple routines for linear algebra and FFT (Fast Fourier Transform) and sophisticated random-number generation.

In [2]:
#importing numpy package
import numpy as np
a=np.array([1,2,3]) #forming an array with 3 elements using array function in numpy
print(a)

[1 2 3]


**Creating 2D arrays:**

In [3]:
x=np.array([[1,2,3],[4,5,6]])
print("The array x=",x)
x1=np.array([1,2,3,4,5],ndmin=2)
print("Array x1 =",x1)

The array x= [[1 2 3]
 [4 5 6]]
Array x1 = [[1 2 3 4 5]]


### *By observing these two arrays, a question comes to mind: **Are the arrays 'x' and 'x1' both 2 dimensional?***

* Yes, both 'x' and 'x1' is 2 dimensional. Here's why,

* In order to check the dimensionality of the array, we will use 'shape' or 'ndim' property. 

* **Shape Property:** Gives the dimension in the form of tuple (n,m) where 
                    n= number of rows and m=number of columns
                    
* **ndim property:** Gives the dimension of the array in the form of integer.

Let's do it! 

In [4]:
print(x.shape)
print(x1.shape) 
x.ndim 

(2, 3)
(1, 5)


2

### *Using **'reshape(n,m)'** function:*

It is used to reshape/reverse the dimension of the array. It takes the elements of the array serially converting it to the reverse array. 

Here's how we use it.

In [6]:
# using reshape function on 'x' and storing it in variable 'x2'.
x2=x.reshape(3,2)
print("Dimesnion of the array 'x' after reshaping = ",x2.shape)

Dimesnion of the array 'x' after reshaping =  (3, 2)


### *Using **'transpose()'** function:*

'transpose()' is used to transpose the dimension of the array.
For e.g, if we have an array 'y' with dimension (2,3), then using transpose function we can reverse the dimension to (3,2).

Here's how we do it.

In [7]:
y=np.array([[1,2,3],[2,2,3]]) #creating an array 'y'
print("Dimension of 'y'= ",y.shape) #checking the dimension of the array y
y1=y.transpose() #using transpose function to reverse the dimension and storing it in the variable y1.
print("Dimension of y after transposing =",y1.shape) #printing the dimension of 'y1'.

Dimension of 'y'=  (2, 3)
Dimension of y after transposing = (3, 2)


### *Lets do **mathematical operations** on arrays/matrices:*
* We have stored the addition of matrices 'x' and 'y' in 'add' variable
* We have stored the multiplication (dot product) of 'x' and 'y1' in the 'mult' variable.

In [15]:
add=x + y
print("x + y = \n",add)

x + y = 
 [[2 4 6]
 [6 7 9]]


In [14]:
#For multiplication, the number of columns of first array = number of rows of the second array. 
# So, we will use 'y1' (the transposed array) as the second array.
mult = x.dot(y1)
print("Multiplication of 'x' and 'y1' = \n",mult)

Multiplication of 'x' and 'y1' = 
 [[14 15]
 [32 36]]


### *Using Trigonometrical functions on above defined arrays/matrices:*

In [19]:
sin=np.sin(mult)
cos=np.cos(mult)
print("sin of (x.y) = \n",sin,"\ncos of (x.y) = \n",cos)

sin of (x.y) = 
 [[ 0.99060736  0.65028784]
 [ 0.55142668 -0.99177885]] 
cos of (x.y) = 
 [[ 0.13673722 -0.75968791]
 [ 0.83422336 -0.12796369]]


We know,
$$ \sin^2{\theta} + cos^2{\theta} = 1 $$

This is exactly whats been done below by taking $$ \theta = x.y1 $$

In [22]:
res=sin**2 + cos**2
print("sin^2(x.y1) + cos^2(x.y1) = \n",res)

sin^2(x.y1) + cos^2(x.y1) = 
 [[1. 1.]
 [1. 1.]]


* Now, what if we dont want the dot(.) at the end of every element in the above matrix. 
* The simplest solution will be to convert the data type of the array to integer which can be done using 'astype' function. 

Here's how its done.

In [26]:
res=res.astype(int)

array([[1, 1],
       [1, 1]])

#### **Greattttt!!!!!!!**
So far, so good.

What if we want to find the sum of the elements of the array?

What if we want to find the minimum value among the elements in the array?

Creating zero matrix of order 1 and order (4,5)

Creating unit matrix

Creating an array 'b' with 30 numbers, serially from 1 to 30, taking dimension (3,10) which suggests 3 rows having 10 columns. 

In [29]:
b=np.arange(30).reshape(3,10)
print(b)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
